# Generated by Django 2.2 on 2020-04-19 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 2, 29, 39, 701154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='observaciones',
            field=models.TextField(default=''),
        ),
    ]
