# Generated by Django 2.2 on 2020-04-19 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0003_auto_20200419_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='simbolo',
            field=models.CharField(choices=[('0', 'Kg'), ('1', 'L'), ('2', 'unidad')], default=('0', 'Kg'), max_length=45),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 2, 55, 54, 873206, tzinfo=utc)),
        ),
    ]
