# Generated by Django 2.2 on 2020-04-19 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0004_auto_20200419_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='simbolo',
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 3, 16, 7, 194819, tzinfo=utc)),
        ),
    ]
