# Generated by Django 2.2 on 2020-04-19 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0005_auto_20200419_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='idmedida',
            new_name='medida',
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 3, 25, 2, 311202, tzinfo=utc)),
        ),
    ]
