# Generated by Django 2.2 on 2020-04-19 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0006_auto_20200419_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacionxarticulo',
            old_name='idarticulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='donacionxarticulo',
            old_name='iddonacion',
            new_name='donacion',
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 3, 33, 5, 845837, tzinfo=utc)),
        ),
    ]
