# Generated by Django 2.2 on 2020-04-19 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0007_auto_20200419_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NatanApp.Medida'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 3, 57, 3, 476295, tzinfo=utc)),
        ),
    ]
