# Generated by Django 2.2 on 2020-04-19 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0008_auto_20200419_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 5, 16, 53, 914001, tzinfo=utc)),
        ),
    ]
