# Generated by Django 2.2 on 2020-04-20 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0014_auto_20200420_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150)),
                ('responsable', models.CharField(default='', max_length=150)),
                ('latitud', models.FloatField(default=-45.54)),
                ('longitud', models.FloatField(default=-45.54)),
                ('meta', models.IntegerField()),
                ('disp', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('listo', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 20, 23, 9, 9, 94489, tzinfo=utc)),
        ),
    ]
