# Generated by Django 2.2.10 on 2020-04-21 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0016_auto_20200421_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 19, 32, 27, 936094, tzinfo=utc)),
        ),
    ]
