# Generated by Django 2.2.10 on 2020-04-22 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0020_auto_20200421_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 1, 30, 49, 185866, tzinfo=utc)),
        ),
    ]
