# Generated by Django 2.2.10 on 2020-04-22 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0025_auto_20200422_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 19, 6, 46, 758967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
