# Generated by Django 2.2.10 on 2020-04-22 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0026_auto_20200422_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 22, 40, 46, 805302, tzinfo=utc)),
        ),
    ]
