# Generated by Django 2.2.10 on 2020-04-22 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0027_auto_20200422_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 23, 52, 35, 33337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
