# Generated by Django 2.2.10 on 2020-04-24 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0028_auto_20200422_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 1, 54, 18, 89130, tzinfo=utc)),
        ),
    ]
