# Generated by Django 2.2.10 on 2020-05-05 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0029_auto_20200424_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 1, 46, 17, 760560, tzinfo=utc)),
        ),
    ]
