# Generated by Django 2.2 on 2020-05-11 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0030_auto_20200504_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='disp',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='meta',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='cantidad_packs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='observacion',
            field=models.TextField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='telefono_responsable',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 52, 58, 819460, tzinfo=utc)),
        ),
    ]
