# Generated by Django 2.2.10 on 2020-05-23 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0030_auto_20200504_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 23, 19, 6, 13, 223124, tzinfo=utc)),
        ),
    ]
