# Generated by Django 2.2 on 2020-05-11 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0031_auto_20200511_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 23, 50, 20, 635160, tzinfo=utc)),
        ),
    ]
