# Generated by Django 2.2 on 2020-05-12 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0033_auto_20200512_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 20, 8, 33, 119293, tzinfo=utc)),
        ),
    ]
