# Generated by Django 2.2.10 on 2020-05-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0031_auto_20200523_1906'),
        ('NatanApp', '0034_auto_20200512_1608'),
    ]

    operations = [
    ]
