# Generated by Django 2.2.10 on 2020-05-23 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NatanApp', '0035_merge_20200523_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 23, 20, 2, 33, 57572, tzinfo=utc)),
        ),
    ]
